name: sote.io
favicon: null
layout_spectrum: 0.51345658255741
typography_spectrum: 0.5678049447014928
title: sote.io - Terveyden kulttuuria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#cacac5'
    - '#464a4c'
    - '#81864c'
    - '#090b0b'
    - '#fafaf6'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
