typography_spectrum: 0.76154
color:
  brandColors:
    - '#fdfdfd'
    - '#5e6869'
    - '#9cacad'
    - '#0e110d'
    - '#cfdb6b'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.23092
analytics:
  google: null
  facebook: null
  twitter: null
name: sote.io
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: sote.io
description: Terveyden kulttuuria
purpose: []
