name: sote.io
favicon: null
layout_spectrum: 0.23092
typography_spectrum: 0.5678049447014928
title: sote.io - Terveyden kulttuuria
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fdfdfd'
    - '#5e6869'
    - '#9cacad'
    - '#0e110d'
    - '#cfdb6b'
  brandStrength: 0.8125
  lightness: 0.75
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
